export interface WaveTeam {
  name: string;
  repoUrl: string;
  appliedToWave: boolean;
  triageDecision: string;
  openIssues: number | null;
  issueGrade: string | null;
  hasCode: boolean | null;
  status: string;
  notes: string;
}

export const WAVE4_TEAMS: WaveTeam[] = [
  {
    name: 'MañanaSeguro',
    repoUrl: 'https://github.com/davz7/MananaSeguro',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 12,
    issueGrade: 'A',
    hasCode: true,
    status: 'Reviewed',
    notes: 'Issues updated based on feedback. Split issues #10 & #11 (too big). Add file paths to #5 & #7. Add test runner details to #4 & #6.',
  },
  {
    name: 'Seyf',
    repoUrl: 'https://github.com/Seyfert-Labs/seyf-app-main',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 22,
    issueGrade: 'A',
    hasCode: true,
    status: 'Reviewed',
    notes: 'Estimated 85–90%. Review issue quality against Drips rubric. Likely needs file paths + acceptance criteria. Messaged on TG 17 Apr.',
  },
  {
    name: 'ACTA',
    repoUrl: 'https://github.com/ACTA-Team/zk-test',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 0,
    issueGrade: null,
    hasCode: true,
    status: 'Team to add issues',
    notes: 'No issues on both repos. Messaged on TG 16 Apr.',
  },
  {
    name: 'TANKO',
    repoUrl: 'https://github.com/Tanko-d/Tanko-d',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 1,
    issueGrade: null,
    hasCode: true,
    status: 'Reviewed',
    notes: 'Only 1 issue — scope concern. Messaged on TG 16 Apr.',
  },
  {
    name: 'Mercato',
    repoUrl: 'https://github.com/mercato-supply-chain/mercato-dapp',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 15,
    issueGrade: null,
    hasCode: true,
    status: 'Review pending',
    notes: '',
  },
  {
    name: 'Proyecto Manná',
    repoUrl: 'https://github.com/kuisser116/Manna',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 3,
    issueGrade: null,
    hasCode: true,
    status: 'Reviewed',
    notes: 'Only 3 issues. Needs more issues + Drips rubric fixes.',
  },
  {
    name: 'Vyn',
    repoUrl: 'https://github.com/Kalebtron1/Project-Vyn',
    appliedToWave: true,
    triageDecision: 'Applied',
    openIssues: 11,
    issueGrade: null,
    hasCode: null,
    status: 'Review issues / chase to apply',
    notes: 'Confirm repo has code. Create issues if missing. Submit to Wave app.',
  },
  {
    name: 'Nuup',
    repoUrl: 'https://github.com/Ander-tsx/NUUP',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: null,
    issueGrade: null,
    hasCode: true,
    status: 'Review pending',
    notes: '',
  },
  {
    name: 'Bimex',
    repoUrl: 'https://github.com/David1984TK/Bimex',
    appliedToWave: false,
    triageDecision: 'Not applied',
    openIssues: 20,
    issueGrade: null,
    hasCode: true,
    status: 'Chase to apply',
    notes: 'Add template, file paths, setup, acceptance criteria. Remove non-code issues #10 & #18. Split #11–13. Add wave label. Messaged on TG 16 Apr.',
  },
  {
    name: 'MicoPay',
    repoUrl: 'https://github.com/ericmt-98/micopay-protocol',
    appliedToWave: false,
    triageDecision: 'Not applied',
    openIssues: 31,
    issueGrade: 'A',
    hasCode: true,
    status: 'Team to add issues',
    notes: 'Estimated 85–90%. Create issues from README decomposition (8–12 issues). Then submit to Wave app. Messaged on TG 16 Apr.',
  },
  {
    name: 'Tonalli',
    repoUrl: 'https://github.com/EmmaSA1/Hack-tonalli',
    appliedToWave: false,
    triageDecision: '',
    openIssues: 28,
    issueGrade: null,
    hasCode: true,
    status: 'Review pending',
    notes: '',
  },
  {
    name: 'Rizo',
    repoUrl: 'https://github.com/nallely-lopez/RizoDAO',
    appliedToWave: false,
    triageDecision: '',
    openIssues: 8,
    issueGrade: null,
    hasCode: null,
    status: 'Reviewed',
    notes: '',
  },
  {
    name: 'Kivo',
    repoUrl: '❓ No repo URL',
    appliedToWave: false,
    triageDecision: 'N/A — no repo',
    openIssues: null,
    issueGrade: null,
    hasCode: null,
    status: 'Chase repo',
    notes: 'Messaged on TG 20 Apr.',
  },
  {
    name: 'Eco Tracer',
    repoUrl: '❓ No repo URL',
    appliedToWave: false,
    triageDecision: 'N/A — no repo',
    openIssues: null,
    issueGrade: null,
    hasCode: null,
    status: 'Chase repo',
    notes: 'Messaged on TG 16 Apr.',
  },
  {
    name: 'Brijex',
    repoUrl: '❓ No repo URL',
    appliedToWave: false,
    triageDecision: 'N/A — no repo',
    openIssues: null,
    issueGrade: null,
    hasCode: null,
    status: 'Chase repo',
    notes: 'Messaged on TG 16 Apr.',
  },
  {
    name: 'Centurion Pay',
    repoUrl: '❓ No repo URL',
    appliedToWave: false,
    triageDecision: 'N/A — no repo',
    openIssues: null,
    issueGrade: null,
    hasCode: null,
    status: 'Chase repo',
    notes: 'Messaged on TG 16 Apr.',
  },
  {
    name: 'Ding Payments',
    repoUrl: 'https://github.com/Ding-Payments/ding-payments',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 0,
    issueGrade: 'D',
    hasCode: true,
    status: 'New — not in TG',
    notes: 'Create issues on both repos. Get added to TG group.',
  },
  {
    name: 'BuenDia / DefiWise',
    repoUrl: 'https://github.com/BuenDia-Builders/defiwise-stellar',
    appliedToWave: true,
    triageDecision: 'Approved (Lucas)',
    openIssues: 0,
    issueGrade: 'D',
    hasCode: true,
    status: 'In triage',
    notes: 'Create issues. Add to TG group.',
  },
  {
    name: 'PayStream',
    repoUrl: 'https://github.com/Vera3289/paystream-contracts',
    appliedToWave: true,
    triageDecision: 'Approved',
    openIssues: 0,
    issueGrade: null,
    hasCode: true,
    status: 'In triage',
    notes: 'Confirm with Warren this is PayStream. Create issues.',
  },
];
